### ISSUE TITLE
復帰した際に例外が発生する場合がある

### ISSUE THREAD

**Issue by yukihane** [yukihane/dq10don#3]
crashlytics 2 の例外:

<pre>
java.lang.RuntimeException: Unable to destroy activity {yukihane.dq10don/yukihane.dq10don.tobatsu.view.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void yukihane.dq10don.tobatsu.presenter.TobatsuPresenter.onDestroy()' on a null object reference
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3706)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3724)
       at android.app.ActivityThread.access$1400(ActivityThread.java:151)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1357)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5254)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void yukihane.dq10don.tobatsu.presenter.TobatsuPresenter.onDestroy()' on a null object reference
       at yukihane.dq10don.tobatsu.view.TobatsuFragment.onDestroy(TobatsuFragment.java:83)
       at android.support.v4.app.Fragment.performDestroy(Fragment.java:2006)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1076)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1126)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1108)
       at android.support.v4.app.FragmentManagerImpl.dispatchDestroy(FragmentManager.java:1954)
       at android.support.v4.app.FragmentActivity.onDestroy(FragmentActivity.java:313)
       at android.support.v7.app.ActionBarActivity.onDestroy(ActionBarActivity.java:169)
       at yukihane.dq10don.tobatsu.view.MainActivity.onDestroy(MainActivity.java:97)
       at android.app.Activity.performDestroy(Activity.java:6169)
       at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1141)
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3693)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3724)
       at android.app.ActivityThread.access$1400(ActivityThread.java:151)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1357)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5254)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
</pre>

**Comment by yukihane** [comment]
原因は、onCreateView で初期化していたフィールドをonDestroyで後かたづけしようとしていたため。
onCreateViewは呼ばれない場合があるので、そのような状況でonDestroyが呼ばれるとNPEになっていた。

参考:
[Android Fragment で onCreateView が呼ばれずに onDestroy が呼ばれることはありますか](http://ja.stackoverflow.com/q/12774)
